### ISSUE TITLE
Project won't compile

### ISSUE THREAD

**Issue by qazt482** [inspire-coding/BmiCalculator#2]
Checked out project and got the following error:

```
/Volumes/projects/Android Studio/architecture samples/BmiCalculator/app/src/main/res/layout/app_bar_with_fragment.xml:37: AAPT: error: resource navigation/navigation_graph (aka com.inspirecoding.bmicalculator:navigation/navigation_graph) not found.
```

**Comment by inspire-coding** [comment]
I tried it out and for me it worked w/o errors.

**Comment by qazt482** [comment]
Is there a specific branch I need to switch to? I am on master and I can see there is no navigation component xml.

**Comment by qazt482** [comment]
Looks like you forgot to commit the navigation xml in master.

**Comment by inspire-coding** [comment]
Yes. This repository is connected to a tutorial on my website [(),](inspirecoding.app) which is not ready yet. Check out this branch: [https://github.com/inspire-coding/BmiCalculator/tree/implement_koin](url)
